// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cedqijldzxzwuprzpgkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlZHFpamxkenh6d3VwcnpwZ2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTY4NzYsImV4cCI6MjA2NTY3Mjg3Nn0.eTPinUMYTQB3shOKVjahkEWn57aEdfooDSi3LxDpN6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);